# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSDPlayground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  inhibit_all_warnings!  #禁止掉警告
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'Texture'
  pod 'XXShield'
  pod 'Aspects'
  pod 'JhtMarquee'
  pod 'SKAutoScrollLabel'

  # Pods for JSDPlayground

end
