# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#supports_swift_versions  '> = 3.0'
target 'JSDPlayground' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
  inhibit_all_warnings!  #禁止掉警告
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'Texture'
  pod 'XXShield'
  pod 'Aspects'
  pod 'JhtMarquee'
  pod 'SKAutoScrollLabel'
  pod 'ReactiveCocoa', '=2.3'
  pod 'JLRoutes', '1.6'
  pod 'HHRouter', '~> 0.1.8'
  pod 'MGJRouter', '~>0.9.0'
  pod 'Routable', '~> 0.1.1'
  pod 'YYCache'

  # Pods for JSDPlayground

end
